<?php

/**
 * Created by PhpStorm.
 * User: smairi_med
 * Date: 17/12/2016
 * Time: 9:51 PM
 */

namespace AppBundle\Repository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticles($page, $nbPerPage) {
        $q = $this->createQueryBuilder('a')
            //->orderBy('a.createdAt', 'DESC')
            ->getQuery();

        // Permet de faire une pagination
        $q
            // On définit l'article à partir de laquelle commencer la liste
            ->setFirstResult(($page - 1) * $nbPerPage)
            // Ainsi que le nombre d'annonce à afficher sur une page
            ->setMaxResults($nbPerPage)
        ;

        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        return new Paginator($q, true);
    }
}
